application:
  name: simple-example-node
  project: getting-started
  publicly_accessible: true
  ram: 512MB
routers:
- name: main
  routes:
  - application_name: simple-example-node
    paths:
    - /
