application:
  name: simple-example-node
  organization: QoveryCommunity
  project: BuildpacksTest
  publicly_accessible: true
  ram: 256MB
  port: 3000
routers:
- name: main
  routes:
  - application_name: simple-example-node
    paths:
    - /

